export type VendorSeedCategory =
  | "venue"
  | "photography"
  | "catering"
  | "music"
  | "florals"
  | "attire";

export type VendorPricingModel =
  | "flat-total"
  | "estimated-total"
  | "per-person"
  | "per-person-plus-fixed";

export interface VendorSeed {
  id: string;
  name: string;
  category: VendorSeedCategory;
  serviceLabel?: string;
  region: string;
  city?: string;
  postalCode?: string;
  coverageAreaIds: string[];
  searchAliases: string[];
  priceMin: number;
  priceMax: number;
  pricingModel: VendorPricingModel;
  baseFeeMin?: number;
  baseFeeMax?: number;
  supportedGuestsMin: number;
  supportedGuestsMax: number;
  styleTags: string[];
  reasonSummary: string;
  websiteUrl?: string;
  portfolioUrl?: string;
  portfolioLabel?: string;
  sourceUrl?: string;
  sourceLabel?: string;
  freshnessLabel?: string;
}

const pfalzTourismWeddingGuideUrl =
  "https://www.pfalz.de/sites/default/files/media/file/2018-07/heiraten_und_feiern_web.pdf";
const trustlocalPhotographySourceUrl =
  "https://trustlocal.de/rheinland-pfalz/neustadt-an-der-weinstra%C3%9Fe/hochzeitsfotograf/";
const trustlocalCateringSourceUrl =
  "https://trustlocal.de/rheinland-pfalz/neustadt-an-der-weinstra%C3%9Fe/catering/";
const trustlocalDjSourceUrl =
  "https://trustlocal.de/rheinland-pfalz/neustadt-an-der-weinstra%C3%9Fe/dj/";
const stefanKietzVenueGuideUrl = "https://www.djstefankietz.de/hochzeitslocations";
const gutRehbachReviewUrl = "https://hochzeits-location.info/hochzeitslocation/gut-rehbach";
const imanBaderReviewUrl =
  "https://www.hair-and-lounge.de/salon/iman-bader-brautstyling-hairstyling-makeup-neustadt-an-der-weinstrasse-67434/";
const ringelblumeReviewUrl =
  "https://www.werkenntdenbesten.de/florist/deidesheim/floristik-ringelblume-aXLFpc";

export const curatedVendorSeeds: ReadonlyArray<VendorSeed> = [
  {
    id: "berlin-spree-loft",
    name: "Spree Loft Atelier",
    category: "venue",
    region: "Berlin",
    coverageAreaIds: ["berlin-core"],
    searchAliases: ["berlin", "mitte", "spree loft atelier"],
    priceMin: 5500,
    priceMax: 8500,
    pricingModel: "flat-total",
    supportedGuestsMin: 50,
    supportedGuestsMax: 120,
    styleTags: ["modern", "natural", "industrial"],
    reasonSummary: "Passt zu Berlin, 80 Gaesten und einem modernen naturnahen Stil."
  },
  {
    id: "berlin-nordlicht-photo",
    name: "Studio Nordlicht",
    category: "photography",
    region: "Berlin",
    coverageAreaIds: ["berlin-core"],
    searchAliases: ["berlin", "studio nordlicht"],
    priceMin: 1800,
    priceMax: 2600,
    pricingModel: "estimated-total",
    supportedGuestsMin: 20,
    supportedGuestsMax: 140,
    styleTags: ["modern", "natural", "editorial"],
    reasonSummary:
      "Trifft den Stil, liegt im Foto-Budget und ist auf urbane Feiern im Berliner Raum ausgerichtet."
  },
  {
    id: "berlin-kranich-catering",
    name: "Kranich Catering",
    category: "catering",
    region: "Berlin",
    coverageAreaIds: ["berlin-core"],
    searchAliases: ["berlin", "kranich catering"],
    priceMin: 3200,
    priceMax: 4100,
    pricingModel: "estimated-total",
    supportedGuestsMin: 40,
    supportedGuestsMax: 120,
    styleTags: ["modern", "seasonal", "natural"],
    reasonSummary:
      "Skaliert gut auf 80 Gaeste, bleibt nah am Catering-Rahmen und passt zu moderner saisonaler Planung."
  },
  {
    id: "potsdam-orangerie-garden",
    name: "Orangerie Garden Hall",
    category: "venue",
    region: "Potsdam",
    coverageAreaIds: ["potsdam-core"],
    searchAliases: ["potsdam", "orangerie garden hall"],
    priceMin: 6200,
    priceMax: 9200,
    pricingModel: "flat-total",
    supportedGuestsMin: 60,
    supportedGuestsMax: 140,
    styleTags: ["classic", "garden", "romantic"],
    reasonSummary: "Gute Ausweichoption in Brandenburg fuer groessere Feierlayouts."
  },
  {
    id: "hassloch-the-space",
    name: "THE SPACE",
    category: "venue",
    serviceLabel: "Urban Loft & Dinner-Location",
    region: "Pfalz",
    city: "Hassloch",
    postalCode: "67454",
    coverageAreaIds: ["67454-radius-40km"],
    searchAliases: ["67454", "hassloch", "the space"],
    priceMin: 4500,
    priceMax: 7000,
    pricingModel: "estimated-total",
    supportedGuestsMin: 30,
    supportedGuestsMax: 90,
    styleTags: ["modern", "industrial", "urban"],
    reasonSummary:
      "Direkt in Hassloch und stark fuer moderne Hochzeitsfeiern, Welcome-Abende oder kleinere Dinner-Formate.",
    websiteUrl: "https://the-space.bar/reservieren/",
    portfolioUrl: "https://the-space.bar/reservieren/",
    sourceUrl: "https://the-space.bar/reservieren/",
    sourceLabel: "Offizielle Reservierungsseite",
    freshnessLabel: "Offizielle Website, Stand April 2026"
  },
  {
    id: "gut-rehbach",
    name: "Gut Rehbach",
    category: "venue",
    serviceLabel: "Scheune, Innenhof & Uebernachtung",
    region: "Pfalz",
    city: "Hassloch",
    postalCode: "67454",
    coverageAreaIds: ["67454-radius-40km"],
    searchAliases: ["gut rehbach", "hassloch", "67454", "fuchsbau"],
    priceMin: 7800,
    priceMax: 12500,
    pricingModel: "estimated-total",
    supportedGuestsMin: 60,
    supportedGuestsMax: 140,
    styleTags: ["natural", "boho", "rustic", "fine-art"],
    reasonSummary:
      "Festscheune, Chalet, Innenhof und Uebernachtungen an einem Ort machen Gut Rehbach zu einer der staerksten Komplett-Loesungen direkt bei Hassloch.",
    websiteUrl: "https://www.gut-rehbach.de/",
    sourceUrl: gutRehbachReviewUrl,
    sourceLabel: "hochzeits-location.info",
    freshnessLabel: "Review- und Locationprofil, Stand April 2026"
  },
  {
    id: "deidesheim-rebe",
    name: "Rebe Deidesheim",
    category: "venue",
    serviceLabel: "Weingut & Eventscheune",
    region: "Pfalz",
    city: "Deidesheim",
    postalCode: "67146",
    coverageAreaIds: ["67454-radius-40km"],
    searchAliases: ["deidesheim", "67146", "rebe deidesheim"],
    priceMin: 6500,
    priceMax: 9800,
    pricingModel: "estimated-total",
    supportedGuestsMin: 50,
    supportedGuestsMax: 120,
    styleTags: ["natural", "romantic", "wine-estate"],
    reasonSummary:
      "Weinbergs-Setting mit Hochzeitserfahrung und guter Passung fuer natuerliche oder romantische Feiern.",
    websiteUrl: "https://www.rebe-deidesheim.de/",
    sourceUrl: "https://www.rebe-deidesheim.de/kontakt",
    sourceLabel: "Offizielle Kontaktseite",
    freshnessLabel: "Offizielle Website, Stand April 2026"
  },
  {
    id: "deidesheimer-hof",
    name: "Deidesheimer Hof",
    category: "venue",
    serviceLabel: "Hotel & Festsaal",
    region: "Pfalz",
    city: "Deidesheim",
    postalCode: "67146",
    coverageAreaIds: ["67454-radius-40km"],
    searchAliases: ["deidesheimer hof", "deidesheim", "67146"],
    priceMin: 165,
    priceMax: 189,
    pricingModel: "per-person",
    supportedGuestsMin: 25,
    supportedGuestsMax: 110,
    styleTags: ["classic", "elegant", "romantic"],
    reasonSummary:
      "Klassisches Hotel-Setting am Marktplatz mit offiziellen Hochzeitspauschalen und klaren Prozessdaten.",
    websiteUrl: "https://www.deidesheimerhof.de/de/feiern3/hochzeitsfeiern/hochzeitsarrangement",
    sourceUrl: "https://www.deidesheimerhof.de/storage/app/media/Documents/Flyer%20Hochzeiten.pdf",
    sourceLabel: "Offizieller Hochzeitsflyer",
    freshnessLabel: "Offizielle Preisinformation, Stand April 2026"
  },
  {
    id: "neustadt-hambacher-schloss",
    name: "Hambacher Schloss",
    category: "venue",
    serviceLabel: "Schloss & Festsaal",
    region: "Pfalz",
    city: "Neustadt an der Weinstrasse",
    coverageAreaIds: ["67454-radius-40km"],
    searchAliases: ["hambacher schloss", "neustadt", "hambach"],
    priceMin: 155,
    priceMax: 210,
    pricingModel: "per-person-plus-fixed",
    baseFeeMin: 1500,
    baseFeeMax: 1500,
    supportedGuestsMin: 40,
    supportedGuestsMax: 100,
    styleTags: ["romantic", "historic", "natural"],
    reasonSummary:
      "Schlosskulisse mit offizieller Hochzeitsbroschuere, freier Trauung und belastbarer Schlechtwetter-Option.",
    websiteUrl: "https://www.hambacherschloss-pfalz.de/",
    sourceUrl: "https://www.hambacherschloss-pfalz.de/hochzeitsbroschuere.pdf",
    sourceLabel: "Offizielle Hochzeitsbroschuere",
    freshnessLabel: "Offizielle Broschuere, Stand April 2026"
  },
  {
    id: "hotel-schloss-edesheim",
    name: "Hotel Schloss Edesheim",
    category: "venue",
    serviceLabel: "Schloss & Gewoelbekeller",
    region: "Pfalz",
    city: "Edesheim",
    postalCode: "67483",
    coverageAreaIds: ["67454-radius-40km"],
    searchAliases: ["schloss edesheim", "hotel schloss edesheim", "67483", "edesheim"],
    priceMin: 7200,
    priceMax: 11800,
    pricingModel: "estimated-total",
    supportedGuestsMin: 50,
    supportedGuestsMax: 90,
    styleTags: ["romantic", "classic", "historic"],
    reasonSummary:
      "Romantisches Schlosshotel mit Gewoelbekeller und sauberem Ablauf fuer mittlere Gesellschaften in der suedlichen Weinstrasse.",
    websiteUrl: "https://www.schloss-edesheim.de/",
    sourceUrl: stefanKietzVenueGuideUrl,
    sourceLabel: "DJ Stefan Kietz Venue Guide",
    freshnessLabel: "Venue-Guide / offizielle Website, Stand April 2026"
  },
  {
    id: "villa-ludwigshoehe",
    name: "Villa Ludwigshoehe",
    category: "venue",
    serviceLabel: "Historische Villa & Gewoelbekeller",
    region: "Pfalz",
    city: "Edenkoben",
    postalCode: "67480",
    coverageAreaIds: ["67454-radius-40km"],
    searchAliases: ["villa ludwigshoehe", "edenkoben", "villa pfalz"],
    priceMin: 4200,
    priceMax: 7600,
    pricingModel: "estimated-total",
    supportedGuestsMin: 25,
    supportedGuestsMax: 50,
    styleTags: ["historic", "romantic", "classic"],
    reasonSummary:
      "Historisches Sommerdomizil mit persoenlicher Atmosphaere und kleineren bis mittleren Gesellschaften im Gewoelbekeller.",
    websiteUrl: "https://villa-pfalz.de/",
    sourceUrl: stefanKietzVenueGuideUrl,
    sourceLabel: "DJ Stefan Kietz Venue Guide",
    freshnessLabel: "Venue-Guide / offizielle Website, Stand April 2026"
  },
  {
    id: "kulturviereck-hassloch",
    name: "Buergerhaus Kulturviereck",
    category: "venue",
    serviceLabel: "Trausaal & Feierhalle",
    region: "Pfalz",
    city: "Hassloch",
    postalCode: "67454",
    coverageAreaIds: ["67454-radius-40km"],
    searchAliases: ["kulturviereck", "buergerhaus", "hassloch", "67454"],
    priceMin: 2200,
    priceMax: 4300,
    pricingModel: "estimated-total",
    supportedGuestsMin: 40,
    supportedGuestsMax: 130,
    styleTags: ["classic", "practical", "civil-ceremony"],
    reasonSummary:
      "Stilvoller Saal mit Hof und Garten zur Mitnutzung direkt in Hassloch, stark fuer standesamtnahe Ablaufe und pragmatische Feiern.",
    websiteUrl: "https://hassloch.de/",
    sourceUrl: pfalzTourismWeddingGuideUrl,
    sourceLabel: "Pfalz.Touristik Hochzeitsguide",
    freshnessLabel: "Touristik-Guide / Stadtportal, Stand April 2026"
  },
  {
    id: "villa-boehm-neustadt",
    name: "Villa Boehm",
    category: "venue",
    serviceLabel: "Stadtvilla & Trauzimmer",
    region: "Pfalz",
    city: "Neustadt an der Weinstrasse",
    postalCode: "67433",
    coverageAreaIds: ["67454-radius-40km"],
    searchAliases: ["villa boehm", "neustadt", "stadtmuseum"],
    priceMin: 1800,
    priceMax: 3200,
    pricingModel: "estimated-total",
    supportedGuestsMin: 20,
    supportedGuestsMax: 60,
    styleTags: ["historic", "civil-ceremony", "classic"],
    reasonSummary:
      "Neo-Renaissance-Stadtvilla fuer intime Trauungen oder elegante Empfaenge mit staedtischem Neustadt-Bezug.",
    websiteUrl: "https://stadtmuseum-neustadt.de/",
    sourceUrl: pfalzTourismWeddingGuideUrl,
    sourceLabel: "Pfalz.Touristik Hochzeitsguide",
    freshnessLabel: "Touristik-Guide / Museumsportal, Stand April 2026"
  },
  {
    id: "freinsheim-rathaus",
    name: "Historisches Rathaus Freinsheim",
    category: "venue",
    serviceLabel: "Historischer Trauort",
    region: "Pfalz",
    city: "Freinsheim",
    postalCode: "67251",
    coverageAreaIds: ["67454-radius-40km"],
    searchAliases: ["freinsheim", "historisches rathaus", "67251"],
    priceMin: 1500,
    priceMax: 2600,
    pricingModel: "estimated-total",
    supportedGuestsMin: 10,
    supportedGuestsMax: 60,
    styleTags: ["historic", "civil-ceremony", "romantic"],
    reasonSummary:
      "Historischer Ratssaal in der Altstadt, interessant fuer Paare mit Fokus auf Atmosphaere und kurzem, schlankem Ablauf.",
    websiteUrl: "https://www.freinsheim.de/leben-wohnen/heiraten/",
    sourceUrl: "https://www.freinsheim.de/leben-wohnen/heiraten/",
    sourceLabel: "Offizielle Heiraten-Seite",
    freshnessLabel: "Offizielle Stadtseite, Stand April 2026"
  },
  {
    id: "klosterruine-limburg",
    name: "Klosterruine Limburg",
    category: "venue",
    serviceLabel: "Historischer Trauort",
    region: "Pfalz",
    city: "Bad Duerkheim",
    postalCode: "67098",
    coverageAreaIds: ["67454-radius-40km"],
    searchAliases: ["klosterruine limburg", "bad duerkheim", "67098"],
    priceMin: 1800,
    priceMax: 3400,
    pricingModel: "estimated-total",
    supportedGuestsMin: 10,
    supportedGuestsMax: 70,
    styleTags: ["historic", "outdoor", "romantic"],
    reasonSummary:
      "Romanische Kulisse hoch ueber Bad Duerkheim, besonders stark fuer freie oder standesamtnahe Momente mit Bildwirkung.",
    websiteUrl: "https://www.bad-duerkheim.de/",
    sourceUrl: pfalzTourismWeddingGuideUrl,
    sourceLabel: "Pfalz.Touristik Hochzeitsguide",
    freshnessLabel: "Touristik-Guide / Stadtportal, Stand April 2026"
  },
  {
    id: "brennofen-ilbesheim",
    name: "Brennofen Ilbesheim",
    category: "venue",
    serviceLabel: "Restaurant, Gewoelbe & Garten",
    region: "Pfalz",
    city: "Ilbesheim",
    postalCode: "76831",
    coverageAreaIds: ["67454-radius-40km"],
    searchAliases: ["brennofen ilbesheim", "ilbesheim", "weinstube brennofen"],
    priceMin: 5400,
    priceMax: 8600,
    pricingModel: "estimated-total",
    supportedGuestsMin: 35,
    supportedGuestsMax: 80,
    styleTags: ["natural", "wine-estate", "romantic"],
    reasonSummary:
      "Gewoelbe, Weinlounge und Garten machen den Brennofen stark fuer mittlere Feiern mit Pfalz-Flair.",
    sourceUrl: stefanKietzVenueGuideUrl,
    sourceLabel: "DJ Stefan Kietz Venue Guide",
    freshnessLabel: "Venue-Guide, Stand April 2026"
  },
  {
    id: "hassloch-nicitello",
    name: "Nicitello Fotografie",
    category: "photography",
    serviceLabel: "Hochzeitsreportage",
    region: "Pfalz",
    city: "Hassloch",
    postalCode: "67454",
    coverageAreaIds: ["67454-radius-40km"],
    searchAliases: ["nicitello", "67454", "hassloch", "marco nici"],
    priceMin: 1800,
    priceMax: 2800,
    pricingModel: "estimated-total",
    supportedGuestsMin: 20,
    supportedGuestsMax: 130,
    styleTags: ["romantic", "natural", "documentary"],
    reasonSummary:
      "Direkt aus Hassloch, klar auf Hochzeitsreportagen in der Pfalz ausgerichtet und nah an natuerlichen Paarstories.",
    websiteUrl: "https://www.nicitello.de/",
    portfolioUrl: "https://www.nicitello.de/portfolio-items/paarshooting-dirmstein-pfalz/",
    sourceUrl: "https://www.nicitello.de/kontakt/",
    sourceLabel: "Offizielle Kontaktseite",
    freshnessLabel: "Offizielle Website, Stand April 2026"
  },
  {
    id: "speyer-foto-speyer",
    name: "Foto Speyer",
    category: "photography",
    serviceLabel: "Reportage & Standesamt",
    region: "Pfalz",
    city: "Speyer",
    postalCode: "67346",
    coverageAreaIds: ["67454-radius-40km"],
    searchAliases: ["foto speyer", "speyer", "67346"],
    priceMin: 1600,
    priceMax: 2200,
    pricingModel: "flat-total",
    supportedGuestsMin: 20,
    supportedGuestsMax: 140,
    styleTags: ["documentary", "classic", "natural"],
    reasonSummary:
      "Speyerer Reportage-Fokus mit oeffentlichen Paketankern fuer standesamtliche Formate bis Tagesbegleitung.",
    websiteUrl: "https://www.foto-speyer.de/hochzeitsfotograf",
    portfolioUrl: "https://www.foto-speyer.de/hochzeitsfotograf",
    sourceUrl: "https://www.foto-speyer.de/hochzeitsfotograf",
    sourceLabel: "Offizielle Angebotsseite",
    freshnessLabel: "Offizielle Website, Stand April 2026"
  },
  {
    id: "pfalz-markus-husner",
    name: "Markus Husner",
    category: "photography",
    serviceLabel: "Dokumentarische Reportage",
    region: "Pfalz",
    city: "Bad Duerkheim",
    coverageAreaIds: ["67454-radius-40km"],
    searchAliases: ["markus husner", "bad duerkheim", "pfalz"],
    priceMin: 1700,
    priceMax: 2600,
    pricingModel: "estimated-total",
    supportedGuestsMin: 20,
    supportedGuestsMax: 120,
    styleTags: ["documentary", "natural", "editorial"],
    reasonSummary:
      "Dokumentarischer Pfalz-Stil mit ruhiger Begleitung und guter Passung fuer entspannte Hochzeitsreportagen.",
    websiteUrl: "https://www.markushusner.com/hochzeitsfotograf/",
    portfolioUrl: "https://www.markushusner.com/hochzeitsfotograf/",
    sourceUrl: "https://www.markushusner.com/hochzeitsfotograf/",
    sourceLabel: "Offizielle Hochzeitsfotografie-Seite",
    freshnessLabel: "Offizielle Website, Stand April 2026"
  },
  {
    id: "neustadt-lina-wissen",
    name: "Lina Wissen Fotografie",
    category: "photography",
    serviceLabel: "Romantische Reportage",
    region: "Pfalz",
    city: "Neustadt an der Weinstrasse",
    postalCode: "67433",
    coverageAreaIds: ["67454-radius-40km"],
    searchAliases: ["lina wissen", "neustadt", "67433", "suedpfalz"],
    priceMin: 1800,
    priceMax: 2600,
    pricingModel: "estimated-total",
    supportedGuestsMin: 20,
    supportedGuestsMax: 120,
    styleTags: ["romantic", "natural", "editorial"],
    reasonSummary:
      "Neustadter Fotografin mit starkem Netzwerk in der Region und romantischem, lichtem Bildstil.",
    websiteUrl: "https://www.linawissen.com/",
    portfolioUrl: "https://www.linawissen.com/",
    sourceUrl: "https://www.linawissen.com/",
    sourceLabel: "Offizielle Portfolio-Seite",
    freshnessLabel: "Offizielle Website, Stand April 2026"
  },
  {
    id: "alexander-strumberger-fotos",
    name: "Alexander Strumberger Fotos & Fotodesign",
    category: "photography",
    serviceLabel: "Paarreportage & Storytelling",
    region: "Pfalz",
    city: "Neustadt an der Weinstrasse",
    coverageAreaIds: ["67454-radius-40km"],
    searchAliases: ["alexander strumberger", "fotodesign", "neustadt fotograf"],
    priceMin: 1200,
    priceMax: 2200,
    pricingModel: "estimated-total",
    supportedGuestsMin: 15,
    supportedGuestsMax: 130,
    styleTags: ["natural", "documentary", "classic"],
    reasonSummary:
      "Trustlocal-Listing mit schneller Reaktionszeit und klarer Storytelling-Ansprache fuer Paare in Neustadt und Umgebung.",
    websiteUrl: "https://fotos-fotodesign.de/",
    portfolioUrl: "https://fotos-fotodesign.de/",
    sourceUrl: trustlocalPhotographySourceUrl,
    sourceLabel: "Trustlocal Hochzeitsfotografen Neustadt",
    freshnessLabel: "Trustlocal, aktualisiert Maerz 2026"
  },
  {
    id: "mihael-klaudija-prebezac",
    name: "Mihael & Klaudija Prebezac",
    category: "photography",
    serviceLabel: "Foto & Bridal Beauty",
    region: "Pfalz",
    city: "Arbeitsbereich Neustadt an der Weinstrasse",
    coverageAreaIds: ["67454-radius-40km"],
    searchAliases: ["mihael prebezac", "klaudija prebezac", "hochzeitsfotografie styling"],
    priceMin: 1900,
    priceMax: 3200,
    pricingModel: "estimated-total",
    supportedGuestsMin: 20,
    supportedGuestsMax: 140,
    styleTags: ["editorial", "romantic", "natural"],
    reasonSummary:
      "Kombiniert Hochzeitsfotografie mit Styling-Kompetenz und hat in Neustadt einen der staerksten aktuellen Review-Scores im Trustlocal-Umfeld.",
    websiteUrl: "https://hochzeiten.prebezac.de/",
    portfolioUrl: "https://hochzeiten.prebezac.de/",
    sourceUrl: trustlocalPhotographySourceUrl,
    sourceLabel: "Trustlocal Hochzeitsfotografen Neustadt",
    freshnessLabel: "Trustlocal, aktualisiert Maerz 2026"
  },
  {
    id: "christian-stumpf-photography",
    name: "Hochzeitsfotograf Christian Stumpf",
    category: "photography",
    serviceLabel: "Ganztagesreportage",
    region: "Pfalz",
    city: "Arbeitsbereich Neustadt an der Weinstrasse",
    coverageAreaIds: ["67454-radius-40km"],
    searchAliases: ["christian stumpf", "hochzeitsfotograf christian stumpf"],
    priceMin: 1800,
    priceMax: 3200,
    pricingModel: "estimated-total",
    supportedGuestsMin: 20,
    supportedGuestsMax: 150,
    styleTags: ["editorial", "romantic", "documentary"],
    reasonSummary:
      "Starkes Review-Profil und klare Positionierung fuer emotionale Ganztagesreportagen mit detailstarken Paarbildern.",
    websiteUrl: "https://hochzeitsfotograf-christianstumpf.de/",
    portfolioUrl: "https://hochzeitsfotograf-christianstumpf.de/",
    sourceUrl: trustlocalPhotographySourceUrl,
    sourceLabel: "Trustlocal Hochzeitsfotografen Neustadt",
    freshnessLabel: "Trustlocal, aktualisiert Maerz 2026"
  },
  {
    id: "daniela-rupp-photoart",
    name: "Daniela Rupp - DR PhotoArt",
    category: "photography",
    serviceLabel: "Reportage & Portrait",
    region: "Pfalz",
    city: "Arbeitsbereich Neustadt an der Weinstrasse",
    coverageAreaIds: ["67454-radius-40km"],
    searchAliases: ["daniela rupp", "dr photoart"],
    priceMin: 1700,
    priceMax: 2800,
    pricingModel: "estimated-total",
    supportedGuestsMin: 20,
    supportedGuestsMax: 130,
    styleTags: ["natural", "classic", "romantic"],
    reasonSummary:
      "Trustlocal-gepruefte Fotografin mit konstant hohem Score und guter Eignung fuer Paare, die Reportage und Portrait verbinden wollen.",
    websiteUrl: "https://danielarupp.de/",
    portfolioUrl: "https://danielarupp.de/",
    sourceUrl: trustlocalPhotographySourceUrl,
    sourceLabel: "Trustlocal Hochzeitsfotografen Neustadt",
    freshnessLabel: "Trustlocal, aktualisiert Maerz 2026"
  },
  {
    id: "roger-rachel-photography",
    name: "Roger Rachel Photography",
    category: "photography",
    serviceLabel: "Fine Art & grosse Reportagen",
    region: "Pfalz",
    city: "Arbeitsbereich Neustadt an der Weinstrasse",
    coverageAreaIds: ["67454-radius-40km"],
    searchAliases: ["roger rachel photography", "roger rachel"],
    priceMin: 2200,
    priceMax: 3600,
    pricingModel: "estimated-total",
    supportedGuestsMin: 25,
    supportedGuestsMax: 180,
    styleTags: ["fine-art", "editorial", "romantic"],
    reasonSummary:
      "Mehr als 700 Hochzeiten laut Trustlocal-Profil und einer der reviewstarken Anbieter fuer groessere Reportagen in der Region.",
    websiteUrl: "https://www.roger-rachel.de/",
    portfolioUrl: "https://www.roger-rachel.de/hochzeitsfotograf-speyer-altrip",
    sourceUrl: trustlocalPhotographySourceUrl,
    sourceLabel: "Trustlocal Hochzeitsfotografen Neustadt",
    freshnessLabel: "Trustlocal, aktualisiert Maerz 2026"
  },
  {
    id: "hassloch-event-taste",
    name: "Event Taste",
    category: "catering",
    serviceLabel: "Full-Service & Genussstationen",
    region: "Pfalz",
    city: "Hassloch",
    postalCode: "67454",
    coverageAreaIds: ["67454-radius-40km"],
    searchAliases: ["event taste", "67454", "hassloch", "fronmuehle"],
    priceMin: 3500,
    priceMax: 5200,
    pricingModel: "estimated-total",
    supportedGuestsMin: 30,
    supportedGuestsMax: 100,
    styleTags: ["modern", "seasonal", "natural"],
    reasonSummary:
      "Lokales Catering- und Eventteam in Hassloch mit starkem Genuss- und Eventfokus fuer moderne Feiern.",
    websiteUrl: "https://www.eventtaste.de/",
    portfolioUrl: "https://www.eventtaste.de/",
    sourceUrl: "https://www.eventtaste.de/",
    sourceLabel: "Offizielle Menue- und Kontaktseite",
    freshnessLabel: "Offizielle Website, Stand April 2026"
  },
  {
    id: "landau-luckies-catering",
    name: "Luckies Catering",
    category: "catering",
    serviceLabel: "Full-Service Catering",
    region: "Pfalz",
    city: "Landau / Herxheim",
    coverageAreaIds: ["67454-radius-40km"],
    searchAliases: ["luckies catering", "landau", "herxheim"],
    priceMin: 3800,
    priceMax: 6000,
    pricingModel: "estimated-total",
    supportedGuestsMin: 50,
    supportedGuestsMax: 150,
    styleTags: ["classic", "natural", "full-service"],
    reasonSummary:
      "Full-Service-Caterer fuer Landau und Herxheim mit Vor-Ort-Beratung und Hochzeitserfahrung.",
    websiteUrl: "https://luckies-catering.de/",
    portfolioUrl: "https://luckies-catering.de/",
    sourceUrl: "https://luckies-catering.de/",
    sourceLabel: "Offizielle Catering-Seite",
    freshnessLabel: "Offizielle Website, Stand April 2026"
  },
  {
    id: "speyer-straub-catering",
    name: "Straub Catering",
    category: "catering",
    serviceLabel: "Catering & Venue-Erfahrung",
    region: "Pfalz",
    city: "Speyer",
    coverageAreaIds: ["67454-radius-40km"],
    searchAliases: ["straub catering", "speyer", "rebe deidesheim"],
    priceMin: 4200,
    priceMax: 6500,
    pricingModel: "estimated-total",
    supportedGuestsMin: 50,
    supportedGuestsMax: 160,
    styleTags: ["classic", "natural", "full-service"],
    reasonSummary:
      "Etablierter Caterer aus der Region mit sichtbarer Hochzeitserfahrung an Pfalz-Locations wie der Rebe.",
    websiteUrl: "https://www.straub-catering.de/",
    portfolioUrl: "https://www.straub-catering.de/locations/rebe-deidesheim/",
    portfolioLabel: "Referenz-Location",
    sourceUrl: "https://www.straub-catering.de/locations/rebe-deidesheim/",
    sourceLabel: "Offizielle Location-Referenz",
    freshnessLabel: "Offizielle Website, Stand April 2026"
  },
  {
    id: "mixguru-cocktail-catering",
    name: "MixGuru",
    category: "catering",
    serviceLabel: "Cocktail-Bar & Empfang",
    region: "Pfalz / Rhein-Neckar",
    city: "Arbeitsbereich Neustadt an der Weinstrasse",
    coverageAreaIds: ["67454-radius-40km"],
    searchAliases: ["mixguru", "cocktail catering", "bar catering"],
    priceMin: 900,
    priceMax: 2200,
    pricingModel: "estimated-total",
    supportedGuestsMin: 20,
    supportedGuestsMax: 140,
    styleTags: ["modern", "urban", "welcome-drinks"],
    reasonSummary:
      "Starker lokaler Trustlocal-Score fuer Cocktail-Catering, interessant als Empfangs- oder Late-Night-Ergaenzung zur Hauptbewirtung.",
    websiteUrl: "https://mixguru.de/en/",
    portfolioUrl: "https://mixguru.de/en/",
    sourceUrl: trustlocalCateringSourceUrl,
    sourceLabel: "Trustlocal Caterer Neustadt",
    freshnessLabel: "Trustlocal, aktualisiert Maerz 2026"
  },
  {
    id: "der-jaeger-kochts",
    name: "Der Jaeger kocht's",
    category: "catering",
    serviceLabel: "Catering, Grillen & Fingerfood",
    region: "Pfalz / Rhein-Neckar",
    city: "Arbeitsbereich Neustadt an der Weinstrasse",
    coverageAreaIds: ["67454-radius-40km"],
    searchAliases: ["der jaeger kochts", "fingerfood catering", "grillen catering"],
    priceMin: 2200,
    priceMax: 4800,
    pricingModel: "estimated-total",
    supportedGuestsMin: 25,
    supportedGuestsMax: 120,
    styleTags: ["rustic", "bbq", "natural"],
    reasonSummary:
      "Trustlocal-Top-Anbieter fuer Fingerfood, Grillen und persoenliche Beratung, geeignet fuer lockere und outdoor-lastige Hochzeitsformate.",
    websiteUrl: "https://www.der-jaeger-kochts.de/",
    portfolioUrl: "https://www.der-jaeger-kochts.de/",
    sourceUrl: trustlocalCateringSourceUrl,
    sourceLabel: "Trustlocal Caterer Neustadt",
    freshnessLabel: "Trustlocal, aktualisiert Maerz 2026"
  },
  {
    id: "basten-kocht",
    name: "Basten kocht",
    category: "catering",
    serviceLabel: "Private Dining & Buffet",
    region: "Pfalz / Rhein-Neckar",
    city: "Arbeitsbereich Neustadt an der Weinstrasse",
    coverageAreaIds: ["67454-radius-40km"],
    searchAliases: ["basten kocht", "gourmetkoch", "private dining"],
    priceMin: 1800,
    priceMax: 3900,
    pricingModel: "estimated-total",
    supportedGuestsMin: 15,
    supportedGuestsMax: 80,
    styleTags: ["seasonal", "modern", "intimate"],
    reasonSummary:
      "Gourmet- und Private-Dining-Ansatz fuer kleinere Gesellschaften mit starkem Fokus auf individuelle Menues.",
    websiteUrl: "https://bastenkocht.de/",
    portfolioUrl: "https://bastenkocht.de/",
    sourceUrl: trustlocalCateringSourceUrl,
    sourceLabel: "Trustlocal Caterer Neustadt",
    freshnessLabel: "Trustlocal, aktualisiert Maerz 2026"
  },
  {
    id: "johannes-staehly-catering",
    name: "Johannes Staehly Metzgerei & Catering",
    category: "catering",
    serviceLabel: "Regionale Kueche & Partyservice",
    region: "Pfalz",
    city: "Arbeitsbereich Neustadt an der Weinstrasse",
    coverageAreaIds: ["67454-radius-40km"],
    searchAliases: ["staehly catering", "metzgerei staehly", "partyservice"],
    priceMin: 2200,
    priceMax: 4400,
    pricingModel: "estimated-total",
    supportedGuestsMin: 30,
    supportedGuestsMax: 130,
    styleTags: ["classic", "regional", "practical"],
    reasonSummary:
      "Regionaler Familienbetrieb mit Trustlocal-Sichtbarkeit fuer bodenstaendige Menues, Buffets und Partyservice.",
    websiteUrl: "https://www.metzgerei-staehly.de/",
    portfolioUrl: "https://www.metzgerei-staehly.de/",
    sourceUrl: trustlocalCateringSourceUrl,
    sourceLabel: "Trustlocal Caterer Neustadt",
    freshnessLabel: "Trustlocal, aktualisiert Maerz 2026"
  },
  {
    id: "hirschalm-eventmanagement",
    name: "Die Hirschalm DenCo GmbH Eventmanagement",
    category: "catering",
    serviceLabel: "Eventlocation & Catering",
    region: "Pfalz",
    city: "Neustadt an der Weinstrasse",
    postalCode: "67433",
    coverageAreaIds: ["67454-radius-40km"],
    searchAliases: ["hirschalm", "denco", "eventmanagement neustadt"],
    priceMin: 2800,
    priceMax: 5600,
    pricingModel: "estimated-total",
    supportedGuestsMin: 30,
    supportedGuestsMax: 120,
    styleTags: ["rustic", "modern", "event"],
    reasonSummary:
      "Kombiniert Eventmanagement, Location-Kompetenz und Catering in Neustadt, sinnvoll fuer Paare mit Wunsch nach wenig Schnittstellen.",
    websiteUrl: "https://www.die-hirschalm.de/",
    portfolioUrl: "https://www.die-hirschalm.de/",
    sourceUrl: trustlocalCateringSourceUrl,
    sourceLabel: "Trustlocal Caterer Neustadt",
    freshnessLabel: "Trustlocal, aktualisiert Maerz 2026"
  },
  {
    id: "marc-nova-dj",
    name: "MARC NOVA Saenger DJ Entertainer",
    category: "music",
    serviceLabel: "DJ, Saenger & Moderation",
    region: "Pfalz / Rhein-Neckar",
    city: "Arbeitsbereich Neustadt an der Weinstrasse",
    coverageAreaIds: ["67454-radius-40km"],
    searchAliases: ["marc nova", "saenger dj entertainer"],
    priceMin: 1800,
    priceMax: 3200,
    pricingModel: "estimated-total",
    supportedGuestsMin: 30,
    supportedGuestsMax: 180,
    styleTags: ["classic", "party", "live-music"],
    reasonSummary:
      "Sehr stark bewerteter DJ mit Entertainer- und Saenger-Profil fuer Paare, die Moderation und Livemusik aus einer Hand suchen.",
    websiteUrl: "https://www.marcnova.com/",
    portfolioUrl: "https://www.marcnova.com/highlights/",
    sourceUrl: trustlocalDjSourceUrl,
    sourceLabel: "Trustlocal DJs Neustadt",
    freshnessLabel: "Trustlocal, aktualisiert Maerz 2026"
  },
  {
    id: "dj-zone-premium",
    name: "DJ Zone",
    category: "music",
    serviceLabel: "DJ & Fotobox",
    region: "Pfalz / Rhein-Neckar",
    city: "Arbeitsbereich Neustadt an der Weinstrasse",
    coverageAreaIds: ["67454-radius-40km"],
    searchAliases: ["dj zone", "premium hochzeiten", "fotobox"],
    priceMin: 1200,
    priceMax: 2400,
    pricingModel: "estimated-total",
    supportedGuestsMin: 30,
    supportedGuestsMax: 180,
    styleTags: ["party", "modern", "all-round"],
    reasonSummary:
      "Top-bewerteter All-in-one-DJ mit Fotobox-Fokus und guter Passung fuer Paare, die weniger externe Dienstleister koordinieren wollen.",
    websiteUrl: "https://www.hochzeitsundeventdj.com/",
    portfolioUrl: "https://www.hochzeitsundeventdj.com/",
    sourceUrl: trustlocalDjSourceUrl,
    sourceLabel: "Trustlocal DJs Neustadt",
    freshnessLabel: "Trustlocal, aktualisiert Maerz 2026"
  },
  {
    id: "dj-jan-mitchell",
    name: "DJ Jan Mitchell",
    category: "music",
    serviceLabel: "Hochzeits DJ & Award Gewinner",
    region: "Pfalz / Rhein-Neckar",
    city: "Arbeitsbereich Neustadt an der Weinstrasse",
    coverageAreaIds: ["67454-radius-40km"],
    searchAliases: ["dj jan mitchell", "jan mitchell", "award dj"],
    priceMin: 1600,
    priceMax: 3000,
    pricingModel: "estimated-total",
    supportedGuestsMin: 30,
    supportedGuestsMax: 180,
    styleTags: ["party", "modern", "all-round"],
    reasonSummary:
      "Ausgezeichneter Hochzeits-DJ mit starkem Review-Profil und guter Passung fuer Paare, die sichere Moderation und volle Tanzflaeche wollen.",
    websiteUrl: "https://www.dj-janmitchell.de/",
    portfolioUrl: "https://www.dj-janmitchell.de/post/dj-oder-livemusik-hochzeitsfeier",
    sourceUrl: trustlocalDjSourceUrl,
    sourceLabel: "Trustlocal DJs Neustadt",
    freshnessLabel: "Trustlocal, aktualisiert Maerz 2026"
  },
  {
    id: "dj-franckey",
    name: "DJ Franckey",
    category: "music",
    serviceLabel: "Hochzeits- & Event-DJ",
    region: "Pfalz / Rhein-Neckar",
    city: "Arbeitsbereich Neustadt an der Weinstrasse",
    coverageAreaIds: ["67454-radius-40km"],
    searchAliases: ["dj franckey", "franckey", "event dj"],
    priceMin: 1100,
    priceMax: 2300,
    pricingModel: "estimated-total",
    supportedGuestsMin: 25,
    supportedGuestsMax: 180,
    styleTags: ["party", "classic", "all-round"],
    reasonSummary:
      "Stark bewerteter Event-DJ fuer klassische Hochzeitsabende mit breiter Musikabdeckung und unkompliziertem Setup.",
    websiteUrl: "https://djfranckey.com/",
    portfolioUrl: "https://djfranckey.com/",
    sourceUrl: trustlocalDjSourceUrl,
    sourceLabel: "Trustlocal DJs Neustadt",
    freshnessLabel: "Trustlocal, aktualisiert Maerz 2026"
  },
  {
    id: "dj-fisch3r",
    name: "DJ FISCH3R",
    category: "music",
    serviceLabel: "DJ & Partyhits",
    region: "Pfalz / Rhein-Neckar",
    city: "Arbeitsbereich Neustadt an der Weinstrasse",
    coverageAreaIds: ["67454-radius-40km"],
    searchAliases: ["dj fisch3r", "fisch3r", "partyhits dj"],
    priceMin: 1200,
    priceMax: 2400,
    pricingModel: "estimated-total",
    supportedGuestsMin: 25,
    supportedGuestsMax: 170,
    styleTags: ["party", "modern", "late-night"],
    reasonSummary:
      "Gute Option fuer Paare, die einen klaren Party-Fokus und einen sichtbaren Track Record im regionalen DJ-Markt suchen.",
    websiteUrl: "https://dein-dj-party.de/",
    portfolioUrl: "https://dein-dj-party.de/",
    sourceUrl: trustlocalDjSourceUrl,
    sourceLabel: "Trustlocal DJs Neustadt",
    freshnessLabel: "Trustlocal, aktualisiert Maerz 2026"
  },
  {
    id: "dj-williamb",
    name: "DJ WilliamB",
    category: "music",
    serviceLabel: "Hochzeiten & Firmenevents",
    region: "Pfalz / Rhein-Neckar",
    city: "Arbeitsbereich Neustadt an der Weinstrasse",
    coverageAreaIds: ["67454-radius-40km"],
    searchAliases: ["dj williamb", "williamb", "firmenevents dj"],
    priceMin: 1200,
    priceMax: 2500,
    pricingModel: "estimated-total",
    supportedGuestsMin: 30,
    supportedGuestsMax: 180,
    styleTags: ["classic", "party", "all-round"],
    reasonSummary:
      "Solider Event-DJ mit gutem Review-Profil fuer strukturierte Abende, Moderation und breite Zielgruppen auf der Tanzflaeche.",
    portfolioLabel: "Bewertungsprofil",
    sourceUrl: trustlocalDjSourceUrl,
    sourceLabel: "Trustlocal DJs Neustadt",
    freshnessLabel: "Trustlocal, aktualisiert Maerz 2026"
  },
  {
    id: "dj-stefan-kietz",
    name: "DJ Stefan Kietz",
    category: "music",
    serviceLabel: "DJ & Moderation",
    region: "Pfalz / Rhein-Neckar",
    city: "Arbeitsbereich Rhein-Pfalz",
    coverageAreaIds: ["67454-radius-40km"],
    searchAliases: ["dj stefan kietz", "stefan kietz", "hochzeits dj pfalz"],
    priceMin: 1500,
    priceMax: 2900,
    pricingModel: "estimated-total",
    supportedGuestsMin: 30,
    supportedGuestsMax: 180,
    styleTags: ["classic", "party", "moderation"],
    reasonSummary:
      "Langjaehrig sichtbarer Hochzeits-DJ mit eigener Venue-Kompetenz, Moderation und sehr starkem regionalem Review-Ranking.",
    websiteUrl: "https://www.djstefankietz.de/",
    portfolioUrl: "https://www.djstefankietz.de/",
    sourceUrl: "https://www.djstefankietz.de/",
    sourceLabel: "Offizielle DJ-Seite",
    freshnessLabel: "Offizielle Website und Trustlocal, Stand April 2026"
  },
  {
    id: "floristik-ringelblume-deidesheim",
    name: "Floristik Ringelblume",
    category: "florals",
    serviceLabel: "Hochzeitsfloristik & Tischdeko",
    region: "Pfalz",
    city: "Deidesheim",
    postalCode: "67146",
    coverageAreaIds: ["67454-radius-40km"],
    searchAliases: ["floristik ringelblume", "ringelblume deidesheim", "deidesheim floristik"],
    priceMin: 900,
    priceMax: 2600,
    pricingModel: "estimated-total",
    supportedGuestsMin: 20,
    supportedGuestsMax: 150,
    styleTags: ["romantic", "natural", "garden"],
    reasonSummary:
      "Lokaler Floristik-Anbieter in Deidesheim mit Hochzeitsbezug, Tischdeko-Kompetenz und sichtbaren Kundenbewertungen.",
    websiteUrl: "https://www.floristik-ringelblume.de/",
    portfolioUrl: "https://www.floristik-ringelblume.de/hochzeit/",
    sourceUrl: "https://www.floristik-ringelblume.de/",
    sourceLabel: "Offizielle Website",
    freshnessLabel: "Offizielle Website und Bewertungsprofil, Stand April 2026"
  },
  {
    id: "blumen-jast-speyer",
    name: "Blumen Jast",
    category: "florals",
    serviceLabel: "Hochzeitsfloristik & Eventdeko",
    region: "Pfalz",
    city: "Speyer",
    postalCode: "67346",
    coverageAreaIds: ["67454-radius-40km"],
    searchAliases: ["blumen jast", "speyer floristik", "hochzeitsfloristik speyer"],
    priceMin: 1000,
    priceMax: 2800,
    pricingModel: "estimated-total",
    supportedGuestsMin: 20,
    supportedGuestsMax: 180,
    styleTags: ["classic", "romantic", "garden"],
    reasonSummary:
      "Offensiv auf Hochzeitsfloristik und Eventdeko ausgerichtet, dadurch ein guter Kandidat fuer Komplettbilder von Brautstrauss bis Tafel.",
    websiteUrl: "https://www.blumen-jast.de/hochzeitsfloristik-events",
    portfolioUrl: "https://www.blumen-jast.de/hochzeitsfloristik-events",
    sourceUrl: "https://www.blumen-jast.de/hochzeitsfloristik-events",
    sourceLabel: "Offizielle Hochzeitsfloristik-Seite",
    freshnessLabel: "Offizielle Website, Stand April 2026"
  },
  {
    id: "blumenhaus-burkard",
    name: "Blumenhaus Burkard",
    category: "florals",
    serviceLabel: "Floristik & Dekokonzept",
    region: "Pfalz / Rhein-Neckar",
    coverageAreaIds: ["67454-radius-40km"],
    searchAliases: ["blumenhaus burkard", "burkard floristik", "hochzeitsfloristik burkard"],
    priceMin: 800,
    priceMax: 2200,
    pricingModel: "estimated-total",
    supportedGuestsMin: 15,
    supportedGuestsMax: 140,
    styleTags: ["natural", "classic", "romantic"],
    reasonSummary:
      "Regionaler Floristik-Anbieter mit brauchbarer Passung fuer kleinere bis mittlere Dekopakete und persoenliche Abstimmung.",
    websiteUrl: "https://blumen-burkard.de/",
    portfolioUrl: "https://blumen-burkard.de/floristik.htm",
    sourceUrl: "https://blumen-burkard.de/",
    sourceLabel: "Offizielle Website",
    freshnessLabel: "Offizielle Website, Stand April 2026"
  },
  {
    id: "blumen-schad",
    name: "Blumen Schad",
    category: "florals",
    serviceLabel: "Blumen, Dekoration & Hochzeit",
    region: "Pfalz",
    coverageAreaIds: ["67454-radius-40km"],
    searchAliases: ["blumen schad", "schad floristik", "hochzeit schad"],
    priceMin: 900,
    priceMax: 2400,
    pricingModel: "estimated-total",
    supportedGuestsMin: 20,
    supportedGuestsMax: 150,
    styleTags: ["classic", "garden", "romantic"],
    reasonSummary:
      "Floristik-Anbieter mit klarer Hochzeits- und Eventansprache, sinnvoll fuer Paare mit Wunsch nach abgestimmter Deko aus einer Hand.",
    websiteUrl: "https://www.blumen-schad.de/",
    portfolioUrl: "https://www.blumen-schad.de/",
    sourceUrl: "https://www.blumen-schad.de/",
    sourceLabel: "Offizielle Website",
    freshnessLabel: "Offizielle Website, Stand April 2026"
  },
  {
    id: "blumen-oase-frankenthal",
    name: "Blumen Oase",
    category: "florals",
    serviceLabel: "Floristik, Brautstraeusse & Raumdeko",
    region: "Pfalz / Rhein-Neckar",
    coverageAreaIds: ["67454-radius-40km"],
    searchAliases: ["blumen oase", "frankenthal floristik", "brautstrauss frankenthal"],
    priceMin: 700,
    priceMax: 2100,
    pricingModel: "estimated-total",
    supportedGuestsMin: 15,
    supportedGuestsMax: 140,
    styleTags: ["natural", "romantic", "seasonal"],
    reasonSummary:
      "Breiter Floristik-Anbieter fuer Brautstraeusse und Raumdeko, interessant fuer Paare mit klassisch-romantischem Look.",
    websiteUrl: "https://www.blumenoase-frankenthal.de/",
    portfolioUrl: "https://www.blumenoase-frankenthal.de/auswahl/hochzeitsfloristik/",
    sourceUrl: "https://www.blumenoase-frankenthal.de/",
    sourceLabel: "Offizielle Website",
    freshnessLabel: "Offizielle Website, Stand April 2026"
  },
  {
    id: "iman-bader-bridal-styling",
    name: "Iman Bader Brautstyling",
    category: "attire",
    serviceLabel: "Brautstyling & Make-up",
    region: "Pfalz",
    city: "Neustadt an der Weinstrasse",
    postalCode: "67434",
    coverageAreaIds: ["67454-radius-40km"],
    searchAliases: ["iman bader", "brautstyling neustadt", "braut makeup neustadt"],
    priceMin: 350,
    priceMax: 900,
    pricingModel: "estimated-total",
    supportedGuestsMin: 1,
    supportedGuestsMax: 8,
    styleTags: ["romantic", "modern", "editorial"],
    reasonSummary:
      "Sehr sichtbares Brautstyling in Neustadt mit klaren Brautpaketen, Make-up-Fokus und starkem Bewertungsprofil.",
    websiteUrl: "https://imanbader.de/brautpakete/",
    portfolioUrl: "https://imanbader.de/brautpakete/",
    sourceUrl: "https://imanbader.de/brautpakete/",
    sourceLabel: "Offizielle Brautpakete-Seite",
    freshnessLabel: "Offizielle Website und Bewertungsprofil, Stand April 2026"
  },
  {
    id: "marisa-hois-bridal-styling",
    name: "Marisa Hois Make-up Artist",
    category: "attire",
    serviceLabel: "Brautstyling & Hair",
    region: "Pfalz / Rhein-Neckar",
    coverageAreaIds: ["67454-radius-40km"],
    searchAliases: ["marisa hois", "makeup artist marisa hois", "brautstyling marisa"],
    priceMin: 300,
    priceMax: 850,
    pricingModel: "estimated-total",
    supportedGuestsMin: 1,
    supportedGuestsMax: 8,
    styleTags: ["natural", "modern", "romantic"],
    reasonSummary:
      "Regional sichtbare Hair- und Make-up-Artistin fuer Brautlooks mit eher natuerlicher bis moderner Handschrift.",
    websiteUrl: "https://www.marisahois-makeupartist.de/",
    portfolioUrl: "https://www.marisahois-makeupartist.de/pakete-und-zusatzleistungen",
    sourceUrl: "https://www.marisahois-makeupartist.de/",
    sourceLabel: "Offizielle Website",
    freshnessLabel: "Offizielle Website, Stand April 2026"
  },
  {
    id: "makeup-by-mel",
    name: "Make-up by Mel",
    category: "attire",
    serviceLabel: "Brautmake-up & Styling",
    region: "Pfalz / Rhein-Neckar",
    coverageAreaIds: ["67454-radius-40km"],
    searchAliases: ["makeup by mel", "brautmakeup mel", "make up by mel"],
    priceMin: 220,
    priceMax: 650,
    pricingModel: "estimated-total",
    supportedGuestsMin: 1,
    supportedGuestsMax: 6,
    styleTags: ["modern", "glam", "romantic"],
    reasonSummary:
      "Brautmake-up-Anbieter mit oeffentlicher Preisliste, dadurch schnell einsetzbar fuer fruehe Budgetrealitaet im Styling.",
    websiteUrl: "https://makeupbymel.de/",
    portfolioUrl: "https://makeupbymel.de/",
    sourceUrl:
      "https://makeupbymel.de/wp-content/uploads/2017/10/Preisliste-Brautmakeup.compressed.pdf",
    sourceLabel: "Offizielle Preisliste Brautmake-up",
    freshnessLabel: "Offizielle Website und Preisliste, Stand April 2026"
  },
  {
    id: "salon-lerzer-bridal-styling",
    name: "Salon Lerzer",
    category: "attire",
    serviceLabel: "Brautfrisur & Styling",
    region: "Pfalz / Rhein-Neckar",
    coverageAreaIds: ["67454-radius-40km"],
    searchAliases: ["salon lerzer", "brautfrisur lerzer", "bridal styling lerzer"],
    priceMin: 250,
    priceMax: 700,
    pricingModel: "estimated-total",
    supportedGuestsMin: 1,
    supportedGuestsMax: 8,
    styleTags: ["classic", "glam", "romantic"],
    reasonSummary:
      "Salonbasierter Styling-Kandidat fuer Paare, die Hair und Vor-Ort-Begleitung in einem klassischen Setup bevorzugen.",
    websiteUrl: "https://www.salon-lerzer.de/",
    portfolioUrl: "https://www.salon-lerzer.de/salon-haarstudio-lerzer.html",
    sourceUrl: "https://www.salon-lerzer.de/",
    sourceLabel: "Offizielle Website",
    freshnessLabel: "Offizielle Website, Stand April 2026"
  },
  {
    id: "levianne-brautatelier",
    name: "LeVianne Brautatelier",
    category: "attire",
    serviceLabel: "Brautkleider & Anprobe",
    region: "Pfalz / Rhein-Neckar",
    coverageAreaIds: ["67454-radius-40km"],
    searchAliases: ["levianne", "brautatelier", "brautkleid levianne"],
    priceMin: 1200,
    priceMax: 3200,
    pricingModel: "estimated-total",
    supportedGuestsMin: 1,
    supportedGuestsMax: 4,
    styleTags: ["modern", "editorial", "romantic"],
    reasonSummary:
      "Brautatelier fuer Kleidersuche und Stilrichtung, hilfreich sobald der Look wirklich festgezogen werden soll.",
    websiteUrl: "https://levianne.de/",
    portfolioUrl: "https://levianne.de/",
    sourceUrl: "https://levianne.de/",
    sourceLabel: "Offizielle Website",
    freshnessLabel: "Offizielle Website, Stand April 2026"
  },
  {
    id: "saray-brautmoden",
    name: "Saray Brautmoden",
    category: "attire",
    serviceLabel: "Brautmode & Aenderung",
    region: "Pfalz / Rhein-Neckar",
    coverageAreaIds: ["67454-radius-40km"],
    searchAliases: ["saray brautmoden", "saray", "brautmode saray"],
    priceMin: 900,
    priceMax: 2800,
    pricingModel: "estimated-total",
    supportedGuestsMin: 1,
    supportedGuestsMax: 4,
    styleTags: ["classic", "glam", "romantic"],
    reasonSummary:
      "Brautmoden-Anbieter fuer eine breitere Kleiderauswahl mit klassischer Beratung und Anpassungsfokus.",
    websiteUrl: "https://saray-brautmoden.de/",
    portfolioUrl: "https://saray-brautmoden.de/brautkleid-modell-carmen/",
    sourceUrl: "https://saray-brautmoden.de/",
    sourceLabel: "Offizielle Website",
    freshnessLabel: "Offizielle Website, Stand April 2026"
  }
];
